server:
  port: 8767
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://dengfeng1:8001/eureka/ #,http://dengfeng2:8002/eureka/,http://dengfeng3:8003/eureka/
  instance:
     instance-id: springcloudelectronic
     #prefer-ip-address: true

spring:
  application:
    name: pay-service
  #mysql数据库连接信息
  datasource:
        name: electronic
        type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: mengzj
        password: mengzj
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  #redis数据库连接信息      
  #redis:
    #host: 106.15.185.133
    #password: 123456
    #port: 6379
    #pool:
      #max-idle: 100
      #min-idle: 1
      #max-active: 1000
      #max-wait: -1
  ##activemq连接信息
  #activemq:
    #broker-url: tcp://localhost:61616
    #in-memory: true
    #pool:
      #enabled: false

mybatis:
   type-aliases-package: com.shop.electronic.payapi.entity
   mapper-locations: classpath:mapper/*.xml

info:
   version: $project.version$
   artifactId: $project.artifactId$
   name: "孟志军"
   tel: "15135247658"
   app: "electronic"
   status: "major"  
   company: "www.dengfeng.com"